require('dotenv').config();
const mongoose = require('mongoose');

const connectDB = require('./config/db');
const Category = require('./models/Category');
const Product = require('./models/Product');
const Seller = require('./models/Seller');
const Customer = require('./models/Customer');
const Admin = require('./models/Admin');

const CATEGORIES = [
  { name: 'Electronics', slug: 'electronics', icon: '💻', sortOrder: 1 },
  { name: 'Mobiles', slug: 'mobiles', icon: '📱', sortOrder: 2 },
  { name: 'Fashion', slug: 'fashion', icon: '👕', sortOrder: 3 },
  { name: 'Beauty & Health', slug: 'beauty-health', icon: '💄', sortOrder: 4 },
  { name: 'Home & Living', slug: 'home-living', icon: '🏠', sortOrder: 5 },
  { name: 'Appliances', slug: 'appliances', icon: '🔌', sortOrder: 6 },
  { name: 'Grocery', slug: 'grocery', icon: '🍎', sortOrder: 7 },
  { name: 'Sports', slug: 'sports', icon: '⚽', sortOrder: 8 },
  { name: 'Books', slug: 'books', icon: '📚', sortOrder: 9 },
  { name: 'Toys', slug: 'toys', icon: '🧸', sortOrder: 10 },
  { name: 'Automotive', slug: 'automotive', icon: '🚗', sortOrder: 11 },
];

async function seed() {
  await connectDB();
  console.log('Connected to DB. Seeding...');

  // Clear existing
  await Promise.all([
    Category.deleteMany({}),
    Product.deleteMany({}),
    Seller.deleteMany({}),
    Customer.deleteMany({}),
    Admin.deleteMany({}),
  ]);

  // Seed categories
  const cats = await Category.insertMany(CATEGORIES);
  const catMap = Object.fromEntries(cats.map(c => [c.slug, c._id]));
  console.log('Categories seeded');

  // Seed sellers (using create one-by-one so pre-save hash hook runs)
  const sellerData = [
    { shopName: 'ZoneTech India', ownerName: 'Raman Khanna', email: 'raman@zonetech.in', password: 'password123', phone: '+91 98765 43210', status: 'approved', storeDescription: 'Authorized flagship supplier of premium elite laptops.' },
    { shopName: 'Horizon Telecom', ownerName: 'Priya Patel', email: 'priya@horizon.com', password: 'password123', phone: '+91 98765 43211', status: 'approved', storeDescription: 'Direct source for top-tier smartphones and official accessories.' },
    { shopName: 'Vogue Trends', ownerName: 'Siddharth Roy', email: 'sid@vogue.co', password: 'password123', phone: '+91 98765 43212', status: 'approved', storeDescription: 'Designer casual and semi-formal luxury menswear.' },
    { shopName: 'Smart Home Automation', ownerName: 'Amrit Pal', email: 'support@smarthome.in', password: 'password123', phone: '+91 98765 43213', status: 'approved', storeDescription: 'Premium smart home devices and automation products.' },
  ];
  const sellers = await Promise.all(sellerData.map(s => Seller.create(s)));
  console.log('Sellers seeded');

  // Seed customers
  await Promise.all([
    Customer.create({ name: 'Aarav Sharma', email: 'aarav@gmail.com', password: 'password123', phone: '+91 98765 43210', isVerified: true }),
    Customer.create({ name: 'Maya Roy', email: 'maya@gmail.com', password: 'password123', phone: '+91 98765 43211', isVerified: true }),
  ]);
  console.log('Customers seeded');

  // Seed admin
  await Admin.create({ name: 'Root Administrator', email: 'admin@buyzone.com', password: 'password123', role: 'superadmin' });
  console.log('Admin seeded: admin@buyzone.com / password123');

  // Seed products
  const products = [
    {
      seller: sellers[0]._id,
      name: 'ZoneBook Pro Ultra 15.6" OLED Thin & Light Laptop',
      slug: 'zonebook-pro-ultra-156-oled-laptop',
      sku: 'BZ-EL-001',
      category: catMap['electronics'],
      brand: 'ZoneTech',
      price: 120000,
      discount: 25,
      finalPrice: 89999,
      stock: 12,
      status: 'approved',
      isFeatured: true,
      isFlashSale: true,
      description: 'The ultimate power notebook designed for content creators, software developers, and professionals. Experience blinding speeds and dual-fan quiet cooling systems.',
      specifications: [
        { key: 'Processor', value: 'Intel Core i7 13th Gen' },
        { key: 'RAM', value: '16 GB LPDDR5' },
        { key: 'Storage', value: '1 TB NVMe SSD' },
        { key: 'Display', value: '15.6" OLED UHD 4K' },
      ],
      images: ['https://images.unsplash.com/photo-1496181130204-755241524eab?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.8, count: 128 },
      totalSold: 450,
      tags: ['laptop', 'oled', 'ultrabook'],
    },
    {
      seller: sellers[1]._id,
      name: 'BUYZONE Horizon Pro 5G SmartPhone (256GB, Silk Blue)',
      slug: 'buyzone-horizon-pro-5g-smartphone-256gb',
      sku: 'BZ-MO-102',
      category: catMap['mobiles'],
      brand: 'Horizon',
      price: 35000,
      discount: 29,
      finalPrice: 24999,
      stock: 50,
      status: 'approved',
      isFeatured: true,
      description: "Capture professional cinematic shots and explore limitless cloud capabilities with BUYZONE's signature sleek smartphone offering.",
      specifications: [
        { key: 'Display', value: '6.7 inch AMOLED 120Hz' },
        { key: 'Camera', value: '108MP + 12MP + 5MP' },
        { key: 'Battery', value: '5000 mAh with 80W Charger' },
        { key: 'Processor', value: 'Snapdragon 8 Gen 2' },
      ],
      images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.5, count: 89 },
      totalSold: 290,
      tags: ['mobile', '5g', 'smartphone'],
    },
    {
      seller: sellers[2]._id,
      name: 'Signature Cotton Slim Fit Casual Shirt',
      slug: 'signature-cotton-slim-fit-casual-shirt',
      sku: 'BZ-FA-550',
      category: catMap['fashion'],
      brand: 'Vogue',
      price: 2999,
      discount: 57,
      finalPrice: 1299,
      stock: 120,
      status: 'approved',
      description: 'Tailored for perfect flexibility and sophisticated daily wear. Designed to pair seamlessly with raw denim or tailored chinos.',
      specifications: [
        { key: 'Material', value: '100% Premium Cotton' },
        { key: 'Fit', value: 'Slim Fit' },
        { key: 'Sleeve', value: 'Full Sleeve' },
      ],
      images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.2, count: 45 },
      totalSold: 125,
      tags: ['shirt', 'cotton', 'casual'],
    },
    {
      seller: sellers[3]._id,
      name: 'Smart RoboClean Vacuum Mop with Auto-Docking',
      slug: 'smart-roboclean-vacuum-mop-auto-docking',
      sku: 'BZ-AP-091',
      category: catMap['appliances'],
      brand: 'SmartClean',
      price: 29999,
      discount: 37,
      finalPrice: 18999,
      stock: 15,
      status: 'approved',
      isFeatured: true,
      description: 'Set schedules, monitor clean lines, and command cleaning routines via mobile with our premium autonomous robo-vacuum mop.',
      specifications: [
        { key: 'Suction Power', value: '3200 Pa Super Power' },
        { key: 'Navigation', value: 'LDS Lidar Navigation v4' },
        { key: 'App integration', value: 'Alexa & Google Assistant' },
      ],
      images: ['https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.6, count: 67 },
      totalSold: 200,
      tags: ['vacuum', 'robot', 'smart home'],
    },
    {
      seller: sellers[0]._id,
      name: 'SoundWave Pro Wireless Noise Cancelling Headphones',
      slug: 'soundwave-pro-wireless-noise-cancelling-headphones',
      sku: 'BZ-EL-002',
      category: catMap['electronics'],
      brand: 'ZoneTech',
      price: 12999,
      discount: 23,
      finalPrice: 9999,
      stock: 35,
      status: 'approved',
      isFeatured: true,
      description: 'Premium 40-hour battery life with active noise cancellation. Perfect for travel, office and workouts.',
      specifications: [
        { key: 'Battery', value: '40 Hours' },
        { key: 'Driver Size', value: '40mm Dynamic' },
        { key: 'Connectivity', value: 'Bluetooth 5.3' },
      ],
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.7, count: 203 },
      totalSold: 520,
      tags: ['headphones', 'wireless', 'anc'],
    },
    {
      seller: sellers[1]._id,
      name: 'ZonePad Ultra Tab 10.9" AMOLED Tablet',
      slug: 'zonepad-ultra-tab-109-amoled',
      sku: 'BZ-EL-003',
      category: catMap['electronics'],
      brand: 'ZoneTech',
      price: 55000,
      discount: 27,
      finalPrice: 39999,
      stock: 20,
      status: 'approved',
      description: 'Work, create, and entertain on the go with the stunning 10.9-inch AMOLED display and all-day battery.',
      specifications: [
        { key: 'Display', value: '10.9" AMOLED 120Hz' },
        { key: 'Processor', value: 'Snapdragon 8cx Gen 3' },
        { key: 'Battery', value: '8000 mAh' },
        { key: 'Storage', value: '256GB UFS 3.1' },
      ],
      images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.4, count: 56 },
      totalSold: 150,
      tags: ['tablet', 'amoled', 'android'],
    },
    {
      seller: sellers[2]._id,
      name: 'Men Premium Running Shoes - Air Cushion',
      slug: 'men-premium-running-shoes-air-cushion',
      sku: 'BZ-FA-551',
      category: catMap['fashion'],
      brand: 'AeroStep',
      price: 5999,
      discount: 33,
      finalPrice: 3999,
      stock: 80,
      status: 'approved',
      description: 'Lightweight air-cushion running shoes with breathable mesh upper. Perfect for marathons and daily runs.',
      specifications: [
        { key: 'Material', value: 'Mesh + Rubber Sole' },
        { key: 'Cushion', value: 'Air Bubble Technology' },
        { key: 'Weight', value: '280g per shoe' },
      ],
      images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.3, count: 182 },
      totalSold: 340,
      tags: ['shoes', 'running', 'sports'],
    },
    {
      seller: sellers[3]._id,
      name: 'Organic Green Tea 100 Bags - Premium Darjeeling',
      slug: 'organic-green-tea-100-bags-darjeeling',
      sku: 'BZ-GR-001',
      category: catMap['grocery'],
      brand: 'TeaGarden',
      price: 799,
      discount: 25,
      finalPrice: 599,
      stock: 200,
      status: 'approved',
      description: 'Pure organic Darjeeling green tea. Rich in antioxidants, sourced from the finest estates.',
      specifications: [
        { key: 'Type', value: 'Green Tea' },
        { key: 'Origin', value: 'Darjeeling, India' },
        { key: 'Bags', value: '100 premium bags' },
      ],
      images: ['https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.6, count: 310 },
      totalSold: 890,
      tags: ['tea', 'organic', 'darjeeling'],
    },
    {
      seller: sellers[0]._id,
      name: 'Vitamin C Brightening Serum 30ml - Dermatologist Tested',
      slug: 'vitamin-c-brightening-serum-30ml',
      sku: 'BZ-BE-001',
      category: catMap['beauty-health'],
      brand: 'GlowLab',
      price: 1999,
      discount: 40,
      finalPrice: 1199,
      stock: 60,
      status: 'approved',
      description: 'Advanced 20% Vitamin C serum with hyaluronic acid. Brightens, hydrates, and reduces dark spots.',
      specifications: [
        { key: 'Volume', value: '30ml' },
        { key: 'Key Ingredient', value: '20% Vitamin C' },
        { key: 'Skin Type', value: 'All Skin Types' },
      ],
      images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.5, count: 145 },
      totalSold: 420,
      tags: ['serum', 'vitamin c', 'skincare'],
    },
    {
      seller: sellers[3]._id,
      name: 'Smart LED TV 43" 4K Ultra HD Android TV',
      slug: 'smart-led-tv-43-4k-ultra-hd-android',
      sku: 'BZ-AP-092',
      category: catMap['appliances'],
      brand: 'ViewMax',
      price: 45000,
      discount: 33,
      finalPrice: 29999,
      stock: 18,
      status: 'approved',
      isFeatured: true,
      description: 'Experience cinema-quality entertainment at home with stunning 4K resolution, Dolby Audio, and built-in Android TV.',
      specifications: [
        { key: 'Screen Size', value: '43 inches' },
        { key: 'Resolution', value: '4K Ultra HD (3840x2160)' },
        { key: 'OS', value: 'Android 11' },
        { key: 'Audio', value: '20W Dolby Audio' },
      ],
      images: ['https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.4, count: 92 },
      totalSold: 180,
      tags: ['tv', '4k', 'android', 'smart tv'],
    },
    {
      seller: sellers[1]._id,
      name: 'Home Decor Macrame Wall Hanging - Boho Style',
      slug: 'home-decor-macrame-wall-hanging-boho',
      sku: 'BZ-HL-001',
      category: catMap['home-living'],
      brand: 'ArtisanCraft',
      price: 1499,
      discount: 33,
      finalPrice: 999,
      stock: 45,
      status: 'approved',
      description: 'Handcrafted boho macrame wall hanging. Add a touch of artisan elegance to any room.',
      specifications: [
        { key: 'Material', value: '100% Cotton Rope' },
        { key: 'Size', value: '60cm x 80cm' },
        { key: 'Style', value: 'Bohemian' },
      ],
      images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.7, count: 78 },
      totalSold: 230,
      tags: ['decor', 'macrame', 'boho', 'handmade'],
    },
    {
      seller: sellers[2]._id,
      name: 'Wireless Gaming Mouse RGB 16000 DPI',
      slug: 'wireless-gaming-mouse-rgb-16000-dpi',
      sku: 'BZ-EL-004',
      category: catMap['electronics'],
      brand: 'GamerPro',
      price: 3999,
      discount: 25,
      finalPrice: 2999,
      stock: 55,
      status: 'approved',
      description: 'Professional wireless gaming mouse with 16000 DPI precision sensor, 7 programmable buttons, and RGB lighting.',
      specifications: [
        { key: 'DPI', value: '200 - 16000 DPI' },
        { key: 'Battery', value: '70 hours' },
        { key: 'Connectivity', value: '2.4GHz Wireless' },
        { key: 'Buttons', value: '7 Programmable' },
      ],
      images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.5, count: 167 },
      totalSold: 390,
      tags: ['gaming', 'mouse', 'wireless', 'rgb'],
    },
    // ── SPORTS ──
    {
      seller: sellers[0]._id,
      name: 'Nivia Storm Football Size 5 - Match Quality',
      slug: 'nivia-storm-football-size-5',
      sku: 'BZ-SP-001',
      category: catMap['sports'],
      brand: 'Nivia',
      price: 1299,
      discount: 23,
      finalPrice: 999,
      stock: 80,
      status: 'approved',
      isFeatured: true,
      description: 'FIFA-approved match quality football. Durable PU exterior with butyl rubber bladder for consistent shape retention.',
      specifications: [
        { key: 'Size', value: 'Size 5 (Standard)' },
        { key: 'Material', value: 'PU Synthetic Leather' },
        { key: 'Bladder', value: 'Butyl Rubber' },
      ],
      images: ['https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.4, count: 210 },
      totalSold: 560,
      tags: ['football', 'soccer', 'sports'],
    },
    {
      seller: sellers[1]._id,
      name: 'Cosco Yoga Mat 6mm Anti-Slip with Carry Bag',
      slug: 'cosco-yoga-mat-6mm-anti-slip',
      sku: 'BZ-SP-002',
      category: catMap['sports'],
      brand: 'Cosco',
      price: 999,
      discount: 30,
      finalPrice: 699,
      stock: 120,
      status: 'approved',
      description: 'Premium 6mm thick yoga mat with anti-slip texture. Includes carry bag and strap. Ideal for yoga, pilates, and floor exercises.',
      specifications: [
        { key: 'Thickness', value: '6mm' },
        { key: 'Material', value: 'TPE Foam' },
        { key: 'Dimensions', value: '183cm x 61cm' },
      ],
      images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.3, count: 185 },
      totalSold: 430,
      tags: ['yoga', 'mat', 'fitness', 'sports'],
    },
    {
      seller: sellers[2]._id,
      name: 'Boldfit Adjustable Dumbbell Set 2kg to 10kg',
      slug: 'boldfit-adjustable-dumbbell-set',
      sku: 'BZ-SP-003',
      category: catMap['sports'],
      brand: 'Boldfit',
      price: 2499,
      discount: 28,
      finalPrice: 1799,
      stock: 40,
      status: 'approved',
      description: 'Adjustable dumbbell set with chrome finish. Perfect for home gym workouts, strength training and muscle building.',
      specifications: [
        { key: 'Weight Range', value: '2kg - 10kg' },
        { key: 'Material', value: 'Cast Iron + Chrome' },
        { key: 'Set Includes', value: '2 Dumbbells + Weight Plates' },
      ],
      images: ['https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.5, count: 98 },
      totalSold: 220,
      tags: ['dumbbell', 'gym', 'fitness', 'sports'],
    },
    // ── BOOKS ──
    {
      seller: sellers[3]._id,
      name: 'Atomic Habits by James Clear - Paperback',
      slug: 'atomic-habits-james-clear-paperback',
      sku: 'BZ-BK-001',
      category: catMap['books'],
      brand: 'Penguin Random House',
      price: 499,
      discount: 36,
      finalPrice: 319,
      stock: 200,
      status: 'approved',
      isFeatured: true,
      description: 'The #1 New York Times bestseller. A proven framework for improving every day. James Clear shares tiny changes that deliver remarkable results.',
      specifications: [
        { key: 'Author', value: 'James Clear' },
        { key: 'Pages', value: '320 pages' },
        { key: 'Language', value: 'English' },
        { key: 'Publisher', value: 'Penguin Random House' },
      ],
      images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.9, count: 1240 },
      totalSold: 2800,
      tags: ['self-help', 'habits', 'bestseller', 'books'],
    },
    {
      seller: sellers[0]._id,
      name: 'Rich Dad Poor Dad by Robert T. Kiyosaki',
      slug: 'rich-dad-poor-dad-kiyosaki',
      sku: 'BZ-BK-002',
      category: catMap['books'],
      brand: 'Plata Publishing',
      price: 399,
      discount: 30,
      finalPrice: 279,
      stock: 180,
      status: 'approved',
      description: 'The #1 personal finance book of all time. Robert Kiyosaki shares the story of his two dads — rich and poor — and the lessons he learned from each.',
      specifications: [
        { key: 'Author', value: 'Robert T. Kiyosaki' },
        { key: 'Pages', value: '336 pages' },
        { key: 'Language', value: 'English' },
      ],
      images: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.7, count: 890 },
      totalSold: 1900,
      tags: ['finance', 'investment', 'bestseller', 'books'],
    },
    {
      seller: sellers[1]._id,
      name: 'The Psychology of Money by Morgan Housel',
      slug: 'psychology-of-money-morgan-housel',
      sku: 'BZ-BK-003',
      category: catMap['books'],
      brand: 'Harriman House',
      price: 449,
      discount: 33,
      finalPrice: 299,
      stock: 150,
      status: 'approved',
      description: 'Timeless lessons on wealth, greed, and happiness. 19 short stories exploring the strange ways people think about money.',
      specifications: [
        { key: 'Author', value: 'Morgan Housel' },
        { key: 'Pages', value: '256 pages' },
        { key: 'Language', value: 'English' },
      ],
      images: ['https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.8, count: 670 },
      totalSold: 1450,
      tags: ['finance', 'psychology', 'money', 'books'],
    },
    // ── TOYS ──
    {
      seller: sellers[2]._id,
      name: 'LEGO Classic Creative Bricks 900 Pieces',
      slug: 'lego-classic-creative-bricks-900',
      sku: 'BZ-TY-001',
      category: catMap['toys'],
      brand: 'LEGO',
      price: 3499,
      discount: 29,
      finalPrice: 2499,
      stock: 60,
      status: 'approved',
      isFeatured: true,
      description: 'Unleash creativity with 900 classic LEGO bricks in 33 colours. Build anything you can imagine. Suitable for ages 4+.',
      specifications: [
        { key: 'Pieces', value: '900 bricks' },
        { key: 'Age Group', value: '4+ years' },
        { key: 'Material', value: 'ABS Plastic' },
      ],
      images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.8, count: 320 },
      totalSold: 780,
      tags: ['lego', 'building', 'creative', 'toys'],
    },
    {
      seller: sellers[3]._id,
      name: 'Hot Wheels 20-Car Gift Pack Assorted',
      slug: 'hot-wheels-20-car-gift-pack',
      sku: 'BZ-TY-002',
      category: catMap['toys'],
      brand: 'Hot Wheels',
      price: 1499,
      discount: 33,
      finalPrice: 999,
      stock: 90,
      status: 'approved',
      description: '20 iconic Hot Wheels die-cast cars in one gift pack. Real riders, ultra-detailed designs. Each car approx 1:64 scale.',
      specifications: [
        { key: 'Pack Size', value: '20 cars' },
        { key: 'Scale', value: '1:64' },
        { key: 'Age Group', value: '3+ years' },
        { key: 'Material', value: 'Die-cast metal + plastic' },
      ],
      images: ['https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.6, count: 450 },
      totalSold: 1100,
      tags: ['cars', 'diecast', 'hot wheels', 'toys'],
    },
    {
      seller: sellers[0]._id,
      name: 'Funskool Monopoly Classic Board Game',
      slug: 'funskool-monopoly-classic-board-game',
      sku: 'BZ-TY-003',
      category: catMap['toys'],
      brand: 'Funskool',
      price: 899,
      discount: 22,
      finalPrice: 699,
      stock: 75,
      status: 'approved',
      description: 'The world\'s favourite property trading board game. Buy, sell, and trade properties to become the wealthiest player. Ages 8+.',
      specifications: [
        { key: 'Players', value: '2-8 players' },
        { key: 'Age Group', value: '8+ years' },
        { key: 'Includes', value: 'Board, tokens, cards, dice, houses, hotels' },
      ],
      images: ['https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.5, count: 280 },
      totalSold: 640,
      tags: ['monopoly', 'board game', 'family', 'toys'],
    },
    // ── AUTOMOTIVE ──
    {
      seller: sellers[1]._id,
      name: 'Michelin Pilot Sport 4 Car Tyre 185/65 R15',
      slug: 'michelin-pilot-sport-4-tyre-185-65-r15',
      sku: 'BZ-AU-001',
      category: catMap['automotive'],
      brand: 'Michelin',
      price: 6999,
      discount: 14,
      finalPrice: 5999,
      stock: 30,
      status: 'approved',
      isFeatured: true,
      description: 'Premium performance tyre with superior wet and dry grip. Enhanced fuel efficiency with EverGrip technology.',
      specifications: [
        { key: 'Size', value: '185/65 R15' },
        { key: 'Load Index', value: '88H' },
        { key: 'Season', value: 'All Season' },
        { key: 'Fuel Efficiency', value: 'A Grade' },
      ],
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.6, count: 88 },
      totalSold: 145,
      tags: ['tyre', 'michelin', 'car', 'automotive'],
    },
    {
      seller: sellers[2]._id,
      name: 'Viper Car Dash Camera 4K Ultra HD with Night Vision',
      slug: 'viper-car-dash-camera-4k-night-vision',
      sku: 'BZ-AU-002',
      category: catMap['automotive'],
      brand: 'Viper',
      price: 8999,
      discount: 33,
      finalPrice: 5999,
      stock: 45,
      status: 'approved',
      description: '4K ultra HD dash cam with Sony STARVIS sensor for crystal-clear night vision. 170° wide angle, GPS tracking, loop recording.',
      specifications: [
        { key: 'Resolution', value: '4K Ultra HD 3840x2160' },
        { key: 'Field of View', value: '170° Wide Angle' },
        { key: 'Night Vision', value: 'Sony STARVIS Sensor' },
        { key: 'Storage', value: 'Up to 256GB microSD' },
      ],
      images: ['https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.4, count: 124 },
      totalSold: 290,
      tags: ['dash cam', 'camera', '4k', 'automotive'],
    },
    {
      seller: sellers[3]._id,
      name: 'Amaron Hi-Life Car Battery 55B24L 45Ah',
      slug: 'amaron-hilife-car-battery-55b24l',
      sku: 'BZ-AU-003',
      category: catMap['automotive'],
      brand: 'Amaron',
      price: 5499,
      discount: 9,
      finalPrice: 4999,
      stock: 25,
      status: 'approved',
      description: 'Amaron Hi-Life maintenance-free car battery. Silver calcium alloy for extra life and reliability. 36-month warranty.',
      specifications: [
        { key: 'Capacity', value: '45Ah' },
        { key: 'Voltage', value: '12V' },
        { key: 'Warranty', value: '36 months' },
        { key: 'Type', value: 'Maintenance Free' },
      ],
      images: ['https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&auto=format&fit=crop&q=60'],
      ratings: { average: 4.3, count: 67 },
      totalSold: 110,
      tags: ['battery', 'amaron', 'car', 'automotive'],
    },
  ];

  await Product.insertMany(products);
  console.log(`${products.length} products seeded`);

  console.log('\n✅ Seed complete!');
  console.log('Customer login: aarav@gmail.com / password123');
  console.log('Seller login:   raman@zonetech.in / password123');
  console.log('Admin login:    admin@buyzone.com / password123');

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch(err => {
  console.error('Seed failed:', err);
  process.exit(1);
});
